### ISSUE TITLE
Release version v1.0.49

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1245]
This issue summarizes all migration tasks which need to be performed when deploying v1.0.49 (e.g. mongo db schema changes, elasticsearch index changes, import data changes,...):

**Comment by dkatzberg** [comment]
- [ ] #1180 Change DB - Uniques of indexinDataSet
- [ ] #1180 Reindex Elasticsearch

**Comment by dkatzberg** [comment]
- [ ] Reimport Variables with the correct order in the xml (#1180)
- [ ] Reimport the questions with the field "indexInInstrument" within the json files (#1226)
