### ISSUE TITLE
Release version v1.0.53

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1302]
- [x] Reindex All Indicies (#1229 , #1183, #1258)
- [x] Add dataType to Survey for import. Mandatory field. (#1258) @svietgen
- [x] Reimport all data from all projects (#1301) @svietgen
