### ISSUE TITLE
Cockpit for data providers

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1398]
### Role
- [x] We need to implement the role "Datengeber"/"data provider" (gesis term) who has certain rights (see #1439)

### project overview
- [x] We need the `Cockpit` to give an overview over the metadata provision status to the FDZ-DZHW
  - [x] project configuration
    - [x] add specific data provider to project (import data providers from DLP?) #1842
    - [x] documentation standard ~(import string for _which_ documentation standard from DLP?)~ only by object (or type?) #1843
- [x] we want to assign ~types~ projects between publishers and data provider  #1844 

### else: 💡 
- [x] "report" status of project to DLP-Cockpit? #1844
  - ~aggregated status, such as "in progress", "approved, not yet released", "released"~ done via "Erwartet / Datengeber Fertig / Publisher Fertig"

**Comment by dkatzberg** [comment]
@UteH Please update this issue after your meeting about the third point in jan / feb.

**Comment by UteH** [comment]
### visualize the chosen **standard of METADATA documentation** esp. for external users   
`"\\faust\Abt4\FDZ\Anleitungen_Richtlinien_Vorlagen\Vorlagen_Richtlinien\Dokumentationsstandards\2018-01-10_4-Stufen-Dokumentationsstandard.xlsx"` > Dokustandard > Metadaten  
(⚠️ these are minimum requirements, users may well chosse Bronze and add some information individually)
  - on level of objects, not attributes

### Was sollte für die Datenherausgabe erfüllt sein? 
|                                                  |                                                        | Bronze | Silber | Gold |
|--------------------------------------------------|--------------------------------------------------------|:--------:|:--------:|:------:|
| study                                            | study > study                                          | x      | x      | x    |
|                                                  | study > authors                                        | x      | x      | x    |
|                                                  | study > attachments > MethodReport (gemдя FDZ-Vorlage) | x      | x      | x    |
| surveys                                          | surveys > surveys                                      | x      | x      | x    |
|                                                  | surveys > attachments > responsrates                   |        |        | x    |
| instruments                                      | instruments > instruments                              | x      | x      | x    |
|                                                  | instruments > Fragebogen                               | x      | x      | x    |
|                                                  | instruments > Variablenfragebogen                      | x      | x      | x    |
|                                                  | instruments > Filterfьhrungsdiagramm                   |        | x      | x    |
|                                                  | instruments > Codierlisten                             | x      | x      | x    |
|                                                  | instruments > Sonstige (z. B. Skalenhandbuch)          |        | x      | x    |
| datasets                                         | dataSets > DataSet                                     | x      | x      | x    |
|                                                  | dataSets > SubDataSets                                 | x      | x      | x    |
|                                                  | dataSets > attachments > DataSetReport / Codebook      | x      | x      | x    |
| questions                                        | questions > questions                                  |        | x      | x    |
|                                                  | Fragetexte: Bilder                                     |        |        | x    |
| variables                                        | name                                                   |        | x      | x    |
|                                                  | surveyNumbers                                          |        | x      | x    |
|                                                  | scaleLevel                                             |        | x      | x    |
|                                                  | panelIdentifier                                        |        | x      | x    |
|                                                  | annotations                                            |        | x      | x    |
|                                                  | accessWays                                             |        | x      | x    |
|                                                  | filterDetails.description                              |        | x      | x    |
|                                                  | filterDetails.expression                               |        |        | x    |
|                                                  | filterDetails.expressionLanguage                       |        |        | x    |
|                                                  | generationDetails.description                          |        | x      | x    |
|                                                  | generationDetails.rule                                 |        | x      | x    |
|                                                  | generationDetails.ruleExpressionLanguage               |        | x      | x    |
|                                                  | derivedVariablesIdentifier                             |        | x      | x    |
|                                                  | relatedQuestionStrings                                 |        | (x)    | x    |
|                                                  | questionNumber                                         |        | x      | x    |
|                                                  | instrumentNumber                                       |        | x      | x    |
|                                                  | DoNotDisplayThousandSeparator                          |        | x      | x    |
|                                                  | fre, Maяzahlen etc (Datensatzexktraktion)              |        | x      | x    |
|                                                  | Missing-Definition auf Variablenebene                  |        | x      | x    |

**Comment by rreitmann** [comment]
Lets design/draw a cockpit mockup in the next refinement...

**Comment by UteH** [comment]
|   | Kupfer klein | Kupfer groß | Bronze | Silber | Gold
-- | -- | :--: | :--: | :--: | :--: | :--
study | study > study | x | x | x | x | x
  | study > authors | x | x | x | x | x
  | study > attachments > MethodReport (gemäß   FDZ-Vorlage) | x | x | x | x | x
surveys | surveys > surveys | x | x | x | x | x
  | surveys > attachments > responsrates |   |   |   |   | x
instruments | instruments > instruments | x | x | x | x | x
  | instruments >   Fragebogen | x | x | x | x | x
  | instruments >   Variablenfragebogen | x | x | x | x | x
  | instruments >   Filterführungsdiagramm |   |   |   | x | x
  | instruments >   Sonstige (Codierlisten) |   | x? | x | x | x
  | instruments > Sonstige (z. B.   Skalenhandbuch) |   |   |   | x | x
datasets | dataSets > DataSet | x | x | x | x | x
  | dataSets > SubDataSets | x | x | x | x | x
  | dataSets > attachments >   DataSetReport (automatisch generiert auf Basis der eingetragenen Metadaten) |   | x |   | x | x
  | dataSets >   attachments > irgendeine Art Codebook (z.B. generiert durch Stata   Codebook-Befehl oder manuell erstelltes Codebook) | x |   | x |   |  
questions | questions > questions |   | x |   | x | x
  | Fragetexte: Bilder |   |   |   |   | x
variables | name |   | x |   | x | x
  | surveyNumbers |   | x |   | x | x
  | scaleLevel |   | x |   | x | x
  | panelIdentifier |   |   |   | x | x
  | annotations |   |   |   | x | x
  | accessWays |   |   |   | x | x
  | filterDetails.description |   |   |   | x | x
  | filterDetails.expression |   |   |   |   | x
  | filterDetails.expressionLanguage |   |   |   |   | x
  | generationDetails.description |   |   |   | x | x
  | generationDetails.rule |   |   |   | x | x
  | generationDetails.ruleExpressionLanguage |   |   |   | x | x
  | derivedVariablesIdentifier |   |   |   | x | x
  | relatedQuestionStrings |   | (x) |   | (x) | x
  | questionNumber |   | x |   | x | x
  | instrumentNumber |   | x |   | x | x
  | DoNotDisplayThousandSeparator |   | x |   | x | x
  | fre, Maßzahlen etc   (Datensatzexktraktion) |   | x |   | x | x
  | Missing-Definition auf Variablenebene |   | x |   | x | x

**Comment by UteH** [comment]
@rreitmann in the last refinement we defined exactly the steps of this issue :ok_hand: I added the new issues int he comment above.

Close after planning.

**Comment by rreitmann** [comment]
@UteH What is blocking the progress of this issue?

**Comment by UteH** [comment]
@rreitmann I updated the issue. I am trying to document the progress of the cockpit with reference to our initial requirements.
We do not need to put this in the sprint.
