### ISSUE TITLE
Release v1.0.61

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1492]
- [x] **Please do all MongoDB changes before deploying!**
- [x] #1466 Reimport all surveys. Update all Dara information with reimported survey information
- [x] #1440 update study.xlsx files
- [x] #1440 Mongo rename fields: `db.getCollection('studies').update({}, {$rename:{"surveySeries":"studySeries"}}, false, true);`

**Comment by dkatzberg** [comment]
- [ ] #1466 Reimport all surveys. Update all Dara information with reimported survey information
- [ ] #1440 update study.xlsx files
