### ISSUE TITLE
Release v1.0.63

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1538]
**Please do all MongoDB changes before deploying!**
- [x] #1440 MongoDB: `db.getCollection('studies').update({}, {$rename:{"surveySeries":"studySeries"}}, false, true);`
- [x] #1454 Remove all images from all questions. Afterwards: reupload all questions of all projects.
Deleting files can be done with:
`db.fs.files.remove({"filename": { $regex: /^\/questions/ }})`

Afterwards the chunks are still present but can be cleaned up with:
```javascript
function removeChunkIfNoOwner(chunk){
  //Look for the parent file
  var parentCount = db.fs.files.find({'_id' : chunk.files_id}).count();

  if (parentCount === 0 ){
     db.fs.chunks.remove({'_id': chunk._id});
     print("Removing chunk " + chunk._id);
  }
}
db.fs.chunks.find().forEach(removeChunkIfNoOwner);
```
- [x] Add Role Data Provider to the MongoDB: `db.getCollection('jhi_authority').insert( { _id: 'ROLE_DATA_PROVIDER' } )`
- [x] rename response rate images (#1528)
```javascript
db.fs.files.find({"filename": { $regex: /^\/surveys\/.*_responserate_/ }}).forEach(function(file) {
    if (file.filename.indexOf("/attachments/") === -1) {
        print("Found file" + file.filename);
        var oldFilename = file.filename;
        var newFilename = file.filename.replace(".svg","");
        print("New filename" + newFilename);
        db.fs.files.update({"filename": oldFilename},{$set: {"filename": newFilename}});
    }
})
```
- [x] delete all active websocket sessions
```javascript
db.getCollection('active_websocket_sessions').remove({})
```
