### ISSUE TITLE
PID registration for variables

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3303]
Has to be split up in different issues
- [x] mapping of metadata to schema of PID provider (see below)
- [x] prepare MDM for PID import. Add new PID attribute to variable detail page
- [x] extract relevant metadata. 
   - [x] send metadata via API to PID provider
- [x] import PIDs and assignment to variables 
- [x] include the PID registration in the release process

API for registration: https://labs.da-ra.de/nfdi/
YouTube-Tutorial for the API: https://youtu.be/fm8T-hlhsXg

Main Report 2022: https://zenodo.org/records/6397367

PID Registration Service Demo Application – how to use the test system
Video/Audio: https://youtu.be/fm8T-hlhsXg (URL)

KonsortSWD Measure 5.1: use cases description extended report - 2023
https://zenodo.org/records/7588944

Software KonsortSWD PID Registration Service - 2023
https://zenodo.org/records/10277054

Software Documentation
KonsortSWD Measure 5.1: extended report on the architecture of the PID registration service - 2023
https://zenodo.org/records/10401641

Documentation of the DIW implementation: https://git.soep.de/kwenzig/pids/-/wikis/home

PID4NFDI: https://base4nfdi.de/projects/pid4nfdi https://os.helmholtz.de/aktuelles/projekte/pid4nfdi/

**Comment by tilovillwock** [comment]
**ToDo**
- [ ] Login?
- [ ] Zuordnung finalisieren

**Mapping**:
| Feld | MDM Zuordnung |
|-----|-------------------|
|studyDOI||
|variableName| Variable::name |
|variableLabel| Variable::label |
|pidProposal| <syntax?> |
|landingPage| <MDM Variable URL> |
|resourceType| Download? |
|title| |
|creators||
|publisher||
|publicationDate||
|availability||
|description||

**Comment by AndyDaniel1** [comment]
**Mapping**:
| Feld | MDM Zuordnung |Beispiel
|-----|-------------------|----|
|studyDOI|doi data package|10.21249/DZHWnac2018:2.0.0 |
|variableName| [Variable::name] |adbi01|
|variableLabel| [Variable::label] |Status of the doctorate |
|pidProposal| 21.T11998/dzwh:[dapid]_[varname]:[dapid_version] |21.T11998/dzwh:nac2018_adbi01:2.0.0|
|landingPage| URL Variablendetailseite + Versionsparameter  |https://metadata.fdz.dzhw.eu/en/variables/var-nac2018-ds1-adbi01?page=1&size=10&type=questions&version=2.0.0 |
|resourceType| variable | variable |
|title| [Variable::name]:[Variable::label] | adbi01:Status of the doctorate |
|creators| author data package| Adrian, Dominik; Ambrasat, Jens; Briedis, Kolja; Friedrich, Christian; Fuchs, Amrei; Geils, Matthias; Kovalova, Iryna; Lange, Janine; Lietz, Almuth; Martens, Bernd; Redeke, Susanne; Ruß, Uwe; Sarcletti, Andreas; Schwabe, Ulrike; Seifert, Moritz; Siegel, Madeleine; Teichmann, Carola; Tesch, Jakob; de Vogel, Susanne; Wegner, Antje; Mühleck, Kai; Scheller, Percy; Berroth, Lara; Jänsch, Vanessa K.
|publisher|FDZ-DZHW| FDZ-DZHW|
|publicationDate|publicationdate current version datapackage| Apr 30, 2024|
|availability|Variable:accessways|SUF: On-Site, SUF: Remote-Desktop, SUF: Download, CUF: Download|

**Comment by moellerth** [comment]
@AndyDaniel1 
There are two further questions:

1. The variable label is an i18n-string on MDM side. Should the label language for PID registration be chosen based on the selection for the language of the landing page we implemented for DA|RA? The same issue arises with the landing page for PID registration.
2. The ""availability" field needs to be filled with a fixed value. Only one from the list of [Download, Delivery, OnSite, NotAvailable, Unknown] can be selected. As some data packages have more than one accessway it needs to be decided how this field should be filled for the various combinations of accessways.

**Comment by moellerth** [comment]
**Current state of development:**

- variable metadata can be exported as JSON file via the "external services" entry in the administration menu
- export will take approximately 15 minutes for ~18.500 variables of 28 currently released projects (@AndyDaniel1 we should review if this includes all the projects you want to register variables for)

**API research results**
- Verify:
      - a set of exported variables was verified using the verify endpoint
      - verification will result in a list of errors if there are any
      - result without errors: 
```
# without errors
{
    "documentUri": "10.17889/DZHW:gra2005:1.0.0",
    "constraintViolation": []
}
```

```
# with errors
{
    "documentUri": "10.17889/DZHW:gra2005:1.0.0",
    "constraintViolation": [
        {
            "message": "$.variables[0].availability: does not have a value in the enumeration [Download, Delivery, OnSite, NotAvailable, Unknown]",
            "locationInfo": "$.variables[0].availability"
        }
    ]
}
```

- Register
        -  Authentification was successful
        - registering two test variables was successful
        - successful registrations result in a `jobId` to query further information on the status of the job
- Job status
        - successfully queried the test job resulting in:
```
[
    {
        "position": 0,
        "validationStatus": "valid",
        "validationErrors": [],
        "pid": "21.T11998/dzhw:gra2005-1.0.0_bocc06o_v1_test:1.0.0",
        "registrationResult": "created:201",
        "status": "FINISHED",
        "lastUpdate": "2024-08-02 10:08:40"
    }
]
```

Jobs can also be viewed online:  [Status](https://labs.da-ra.de/nfdi/status) 
A complete PID link will look like this: `https://doi.org/21.T11998/dzhw:gra2005-1.0.0_bocc06o_v1_test:1.0.0`

**Comment by AndyDaniel1** [comment]
> @AndyDaniel1 There are two further questions:
> 
>     1. The variable label is an i18n-string on MDM side. Should the label language for PID registration be chosen based on the selection for the language of the landing page we implemented for DA|RA? The same issue arises with the landing page for PID registration.

For the PID the english version of the landing page should be chosen.

> 
>     2. The ""availability" field needs to be filled with a fixed value. Only one from the list of [Download, Delivery, OnSite, NotAvailable, Unknown] can be selected. As some data packages have more than one accessway it needs to be decided how this field should be filled for the various combinations of accessways.

If a accessway is defined (download delivery onsite) the type should be "available"

if the type is not available it should be set to "not available" 

if the type is unknown it should be set to "unknown".

**Comment by tilovillwock** [comment]
@AndyDaniel1 bezüglich des Feld `variableLabel` muss noch entschieden werden, wie mit der fehlenden Übersetzung umgegangen werden soll: die jetzige Implementierung exportiert standardmäßig die englisch-sprachige Variante. Es gibt aber einige Datensätze, welche nur deutsch-sprachige Labels für die Variablen haben.

Soll also:
a) ein Fallback auf die deutsch-sprachige Variante ergänzt werden oder
b) die Variable dann gar nicht registriert werden

Bezüglich der Implementierung müssen wir uns auch jetzt schon Gedanken über die asynchrone Abarbeitung machen:

Der Workflow der Registrierung der Variablen würde die Veröffentlichung von Projekten aufhalten. Daher müsste dies asynchron im Hintergrund geschehen und vermittelt werden, dass die gesamte Veröffentlichung bei da|ra unter Umständen ein paar Minuten dauern kann.

**Comment by AndyDaniel1** [comment]
A already discussed we need to implement the last 

> @AndyDaniel1 regarding the field `variableLabel` we need to decide how to deal with missing translations: the current implementation only exports variables if there's an english variable label available. However there are quite a lot of datasets that only include variables without a proper translation for their respective labels.
> 
> So either: a) we implement a fallback that uses the German label or b) we don't register the variable

As discussed we implement a)

**Comment by AndyDaniel1** [comment]
For the last phase of implementation we implement the registration process via API in test system (as the provider has no prod system). 

In the release dialog there should be a option to register the variables (de: Registierung von persistenten Identifikatoren (PIDs) für die Variablen des Datenpakets): 
![grafik](https://github.com/user-attachments/assets/b5be851c-919c-4156-8671-048330c10eef)

If the box is checked and the release is initiated the following tests should be run on: 

- Is the service available? 
  - if not display warning de: "Der Dienst zur Registrierung von PIDs für Variablen ist aktuell nicht verfügbar. Sie können den Releaseprozess trotzdem vornehmen und die Variablen später registrieren." en: "The service for registering PIDs for variables is currently not available. You can still carry out the release and register the variables later." --> Questionfield: de: "Soll der Releaseprozess fortgesetzt werden? ja/nein" en: "Should the release process be continued? yes/no"

- are PIDs already registered for the variables in this specific version? 
  - if variables are already registered display warning and skip the registration process: de: "Es sind bereits PIDs für die Variablen in dieser Version registriert, es wird keine neue Registrierung vorgenommen. Der Release des Datenpakets wird wie gewohnt durchgeführt, es sind keine weiteren Aktionen erforderlich." en: "PIDs are already registered for the variables in this version, no new registration will be made. The data package is released as usual, no further action is required."

If the registration process starts without warnings, display de: "Der Releaseprozess wurde angestoßen. Das Datenpaket ist in wenigen Minuten verfügbar. Die Registrierung der PID für Variablen wird im Hintergrund ausgeführt und kann bis zu einer Stunde in Anspruch nehmen." en: "The release process has been initiated. The data package will be available in a few minutes. The registration of the PID for variables is carried out in the background and can take up to an hour."

**Comment by tilovillwock** [comment]
@AndyDaniel1 Regarding the current workflow we need to decide how to communicate if something has gone wrong and if we cancel the entire process if a single set of variables can't be registered because of validation concerns or a different kind of server error. A simple but rather opaque solution would be:

1. Register all variable sets in a single call with da|ra
2. Only on success we save the PID in the respective variable documents
3. The user can verify the status eventually by checking whether the PID is visible in any of the variables

A more fine-grained approach would involve more steps where the variables are being registered in sets (maybe divided up by survey) and failing registrations will send feedback via a dedicated channel like a websocket notification or a special area for data providers.

**Comment by AndyDaniel1** [comment]
@tilovillwock the implementation for the test case works (got a corresponding e-mail). I have one minor remark. The hint that the process could last up to one hour appears only a few seconds. Can it be configured in such a way that it must be actively closed by the user (by clicking on the x)?

**Comment by AndyDaniel1** [comment]
and another minor remark: 
![grafik](https://github.com/user-attachments/assets/3c34a596-4609-452d-a7cf-7988fd4f5b14)

the label should be “Variable PIDs registered” de: “Variable PIDs registered” and analogously for the case that the variables are not registered. 

@moellerth maybe you can edit this today, if not, we will proceed next year here

**Comment by AndyDaniel1** [comment]
@moellerth thanks for the super quick implementation

**Comment by AndyDaniel1** [comment]
@tilovillwock @moellerth Labels are fine now. One thing appeared to me when initiating the registration procedure, when variables are already registered.  When variables are already registered, the concerning warning appears only briefly and then the message appears that the registration process could last for about an hour. The warning that variables should be visible until the user actively closes it.

**Comment by AndyDaniel1** [comment]
![grafik](https://github.com/user-attachments/assets/e7f24d72-bf46-4d34-a037-47458c1f46a3)

**Comment by AndyDaniel1** [comment]
if the variables are already registered, I still receive an email notifying me that the variables have been successfully registered
